Diff

diff --git a/spread-channels/linode-akamai/stack-scripts/StackScript b/spread-channels/linode-akamai/stack-scripts/StackScript
--- a/spread-channels/linode-akamai/stack-scripts/StackScript
+++ b/spread-channels/linode-akamai/stack-scripts/StackScript
@@ -4,6 +4,7 @@
 # <UDF name="token" label="Token: Login with HOSTNAME:8080/login?token=TOKEN" />
 # <UDF name="install_doc_viewer" label="Install doc viewer for PDFs? Takes longer" oneOf="true,false" default="false" />
 # <UDF name="understanding" label="I will open ports tcp:8078-8082 and add DNS A record" oneOf="true,false" default="true" />
+# <UDF name="license_key" label="My BrowserBox license key" example="Purchase at sales@dosaygo.com" />
 
 set -x
 
@@ -21,8 +22,8 @@ get_distro() {
 
 signature="yes"
 # Check if essential fields are present
-if [ -z "$HOSTNAME" ] || [ -z "$USEREMAIL" ]; then
-  echo "Both 'HOSTNAME' and 'USEREMAIL' are required to proceed." >&2
+if [ -z "$HOSTNAME" ] || [ -z "$USEREMAIL" ] || [ -z "$LICENSE_KEY" ]; then
+  echo "All of 'LICENSE_KEY', 'HOSTNAME' and 'USEREMAIL' are required to proceed." >&2
   shutdown now &
   exit 1
 fi
@@ -91,6 +92,7 @@ su - "$username" <<EOF
   git clone https://github.com/BrowserBox/BrowserBox.git
   cd BrowserBox
   ./deploy-scripts/wait_for_hostname.sh "$HOSTNAME"
+  export LICENSE_KEY="$LICENSE_KEY"
   export INSTALL_DOC_VIEWER="$INSTALL_DOC_VIEWER"
   yes | ./deploy-scripts/global_install.sh "$HOSTNAME" "$USEREMAIL"
   if [[ -z "$TOKEN" ]]; then
@@ -98,5 +100,7 @@ su - "$username" <<EOF
   else
     setup_bbpro --port 8080 --token "$TOKEN"
   fi
+  bbcertify
+  export LICENSE_KEY=""
   bbpro
 EOF
