Update

diff --git a/spread-channels/linode-akamai/stack-scripts/StackScript b/spread-channels/linode-akamai/stack-scripts/StackScript
--- a/spread-channels/linode-akamai/stack-scripts/StackScript
+++ b/spread-channels/linode-akamai/stack-scripts/StackScript
@@ -1,25 +1,32 @@
 #!/bin/bash
-# <UDF name="signature" oneOf="yes,no" default="no" label="I agree to the terms and conditions outlined in this StackScript's description.">
-# <UDF name="useremail" label="Your email for the BrowserBox installation Terms and Conditions agreement, including LetsEncrypt terms agreement." example="j.citizen@website.net">
-# <UDF name="hostname" label="HOSTNAME: The fully qualified domain name you use in your A record for this instance." example="hello.example.com">
-# <UDF name="token" label="TOKEN: a secret for the login link (https://HOSTNAME:8080/login?token=TOKEN). Leave blank to get link with SSH.">
+# <UDF name="useremail" label="SIGNATURE EMAIL: I agree to the BrowserBox Terms and Conditions, including LetsEncrypt terms. My email is:" example="jcitizen@website.net">
+# <UDF name="hostname" label="HOSTNAME: The fully-qualified domain name you will put in your DNS A record for this Linode." example="hello.example.com">
+# <UDF name="token" label="TOKEN: a secret for the login link (https://HOSTNAME:8080/login?token=TOKEN). Leave blank to get link with SSH." default="">
 # <UDF name="install_doc_viewer" label="Install document viewer (takes a long time but lets you securely view PDFs, DOCX, etc)" oneOf="true,false" default="false">
+
+signature="yes"
+# Check if essential fields are present
+if [ -z "$hostname" ] || [ -z "$useremail" ]; then
+  echo "Both 'hostname' and 'useremail' are required to proceed." >&2
+  shutdown now &
+  exit 1
+fi
 
 # Check if the user has agreed to the terms and conditions
 if [ "$signature" != "yes" ]; then
-    echo "You must agree to the terms and conditions to use this StackScript." >&2
-    shutdown now &
-    exit 1
+  echo "You must agree to the terms and conditions to use this StackScript." >&2
+  shutdown now &
+  exit 1
 fi
 
 # Function to determine the Linux Distribution
 get_distro() {
   if [ -f /etc/os-release ]; then
-    . /etc/os-release
-    echo "$ID"
+  . /etc/os-release
+  echo "$ID"
   else
-    echo "Distribution not supported"
-    exit 1
+  echo "Distribution not supported"
+  exit 1
   fi
 }
 
@@ -27,35 +34,35 @@ get_distro() {
 distro=$(get_distro)
 case $distro in
   "ubuntu" | "debian")
-    DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y upgrade
-    DEBIAN_FRONTEND=noninteractive apt-get install -y git
-    ;;
+  DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y upgrade
+  DEBIAN_FRONTEND=noninteractive apt-get install -y git
+  ;;
   "centos" | "fedora" | "rhel" | "almalinux")
-    yum update -y
-    yum install -y git
-    ;;
+  yum update -y
+  yum install -y git
+  ;;
   *)
-    echo "Unsupported distribution: $distro"
-    shutdown now & 
-    exit 1
-    ;;
+  echo "Unsupported distribution: $distro"
+  shutdown now & 
+  exit 1
+  ;;
 esac
 
 # Create a new user and add to sudoers
 username="pro"
 if ! id "$username" &>/dev/null; then
-    adduser --disabled-password --gecos "" $username
-    echo "$username ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$username
-    chmod 0440 /etc/sudoers.d/$username
+  adduser --disabled-password --gecos "" $username
+  echo "$username ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$username
+  chmod 0440 /etc/sudoers.d/$username
 fi
 
 # Switch to the new user and run the scripts
 su - "$username" <<EOF
-    git clone https://github.com/BrowserBox/BrowserBox.git
-    cd BrowserBox
-    ./deploy-scripts/wait_for_hostname.sh "$hostname"
-    yes | ./deploy-scripts/global_install.sh "$hostname" "$useremail"
-    export INSTALL_DOC_VIEWER="$install_doc_viewer"
-    setup_bbpro --port 8080 --token "$token"
-    bbpro
+  git clone https://github.com/BrowserBox/BrowserBox.git
+  cd BrowserBox
+  ./deploy-scripts/wait_for_hostname.sh "$hostname"
+  yes | ./deploy-scripts/global_install.sh "$hostname" "$useremail"
+  export INSTALL_DOC_VIEWER="$install_doc_viewer"
+  setup_bbpro --port 8080 --token "$token"
+  bbpro
 EOF
