Manually check

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -72,26 +72,27 @@ jobs:
         echo "::set-output name=url::$complete_url"
         echo $complete_url
 
-    - name: Check integrity route
-      run: |
-        base_url=$(echo "${{ steps.ngrok.outputs.url }}" | grep -oP 'https?://[^/]+')
-        token=$(echo "${{ steps.ngrok.outputs.url }}" | grep -oP 'token=\K[^&]+') # Extract the token parameter
-        integrity_url="${base_url}/integrity?session_token=${token}" # Construct the integrity URL
-        integrity_file_content=$(cat $HOME/BBPRO.INTEGRITY)
-        success=0
-        for i in {1..10}; do
-          echo "Attempt $i to check integrity..."
-          integrity_content=$(curl -L -o /dev/null -s "$integrity_url")
-          if [[ "$integrity_content" == "$integrity_file_content" ]]; then
-            success=1
-            break
-          fi
-          sleep 7
-        done
-        if [[ "$success" -eq 0 ]]; then
-          echo "Error: Integrity check failed for application after 10 attempts."
-          exit 1
-        fi
+#    - name: Check integrity route
+#      run: |
+#        base_url=$(echo "${{ steps.ngrok.outputs.url }}" | grep -oP 'https?://[^/]+')
+#        token=$(echo "${{ steps.ngrok.outputs.url }}" | grep -oP 'token=\K[^&]+') # Extract the token parameter
+#        integrity_url="${base_url}/integrity?session_token=${token}" # Construct the integrity URL
+#        integrity_file_content=$(cat $HOME/BBPRO.INTEGRITY)
+#        success=0
+#        for i in {1..10}; do
+#          echo "Attempt $i to check integrity..."
+#          integrity_content=$(curl -L -o /dev/null -s "$integrity_url")
+#          if [[ "$integrity_content" == "$integrity_file_content" ]]; then
+#            success=1
+#            break
+#          fi
+#          sleep 7
+#        done
+#        if [[ "$success" -eq 0 ]]; then
+#          echo "Error: Integrity check failed for application after 10 attempts."
+#          exit 1
+#        fi
+#
 
     - name: Print ngrok URL
       run: echo "The complete ngrok URL is ${{ steps.ngrok.outputs.url }}"
